#security.basic.enabled=false
#logging.level.org.springframework.web: TRACE
#logging.level.org.hibernate: TRACE
#
#
#spring.security.oauth2.client.registration.google.client-id=<your client id>
#spring.security.oauth2.client.registration.google.client-secret=dev-0d0pu6wujp0nkcw5.eu.auth0.com


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
